// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzu9USm5v9pPevPNeb9xCEuM4TGZbdsXM',
    appId: '1:836574214513:ios:54ef66162ce016e71bded0',
    messagingSenderId: '836574214513',
    projectId: 'prakflutterfirebase-3a556',
    storageBucket: 'prakflutterfirebase-3a556.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzu9USm5v9pPevPNeb9xCEuM4TGZbdsXM',
    appId: '1:836574214513:ios:54ef66162ce016e71bded0',
    messagingSenderId: '836574214513',
    projectId: 'prakflutterfirebase-3a556',
    storageBucket: 'prakflutterfirebase-3a556.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr20sIAovpyqwQAG5x4FKJdcRVqzLgllE',
    appId: '1:836574214513:web:af39dfc241c62e1d1bded0',
    messagingSenderId: '836574214513',
    projectId: 'prakflutterfirebase-3a556',
    authDomain: 'prakflutterfirebase-3a556.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-3a556.appspot.com',
    measurementId: 'G-X95G33QRQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpY-jiKTbk0uBQOxBpyDqJiWOb2ot83u0',
    appId: '1:836574214513:android:fda8be8ba9fecfe51bded0',
    messagingSenderId: '836574214513',
    projectId: 'prakflutterfirebase-3a556',
    storageBucket: 'prakflutterfirebase-3a556.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr20sIAovpyqwQAG5x4FKJdcRVqzLgllE',
    appId: '1:836574214513:web:0b952869cae9dc361bded0',
    messagingSenderId: '836574214513',
    projectId: 'prakflutterfirebase-3a556',
    authDomain: 'prakflutterfirebase-3a556.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-3a556.appspot.com',
    measurementId: 'G-Y20GE48ME0',
  );

}